import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Header from '@/components/layout/header'
import './globals.css'
import Footer from '@/components/layout/footer'
import { GlobalStoreProvider } from '@/providers/store-provider'

const averta = localFont({
  src: [
    {
      path: './fonts/Averta-Extrathin.otf',
      weight: '100',
      style: 'normal',
    },
    {
      path: './fonts/Averta-Thin.otf',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/Averta-Light.otf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/Averta-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Averta-Semibold.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Averta-Bold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/Averta-ExtraBold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Averta-Black.otf',
      weight: '800',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${averta.className} antialiased scroll-smooth`}>
        <GlobalStoreProvider>
          <Header />
          {children}
          <Footer />
        </GlobalStoreProvider>
      </body>
    </html>
  )
}
